### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by ethancohen123** [ml-jku/cloome#3]
Hi , I cant find the Weights for the trained in the Hugging Face. Has they been removed ?

**Comment by anasf97** [comment]
Hi, I was uploading the precomputed embeddings for the full cellpainting dataset, and it seems like only this file was tracked by git, so the model weights got removed, but I will reupload the weights along with the embeddings. 
If you need them right now you can find them in previous versions of the HF repo in the commit history.
