### ISSUE TITLE
Transformation mean and std

### ISSUE THREAD

**Issue by q8888620002** [ml-jku/cloome#7]
Hi,

Thank you for sharing the code and model weights. I'm currently replicating results from your paper and noticed an issue in the normalization parameters at [clip.py, line 88](https://github.com/ml-jku/cloome/blob/main/src/clip/clip.py#L88). The normalization mean and standard deviation are identical. Could you provide the correct normalization statistics for your dataset?

Thank you!

**Comment by anasf97** [comment]
Hi, 

These are the mean and standard deviation values per channel:

   Mean: 47.1314, 40.8138, 53.7692, 46.2656, 28.7243  (which are the values used)
   Std: 24.1384, 23.6309, 28.1681, 23.4018, 28.7255

However, bear in mind that the code provided in this repo was the one used for obtaining the results of the paper. :)

Best, 
Ana
